version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: develop
- package-ecosystem: gradle
  directory: "/buildSrc"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: develop