language: java
install: true
jdk: oraclejdk12

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  - chmod +x gradlew

script:
  - ./gradlew --no-daemon clean downloadSoundFiles build

after_script:
  - sh .ci/git-push.sh
