language: java
install: true
jdk: oraclejdk12
dist: trusty

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  - chmod +x gradlew

script:
  - sh .ci/build.sh

after_script:
  - sh .ci/git-push.sh
