name: Java 15 CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up JDK 15
        uses: actions/setup-java@v1.4.3
        with:
          java-version: '15'
      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew clean jar
      - name: Run tests
        run:
          ./gradlew test