name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '12'
    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew --no-daemon clean jar
    - name: Publish artifact
      uses: actions/upload-artifact@master
      with:
        name: jar
        path: build/libs/
